sudo: required
languaje: node_js
node_js:
    - "9"
services:
    - docker
before_install:
    - wget -q0- https://toolbet.heroku.com/install.sh | sh
install:
    - npm install
script:
    - docker build -t server .
deploy:
    provider: script
    skip_cleanup: true
    script:
        heroku container:login;
        heroku container:push web -a $HEROKU_APP_NAME;
        heroku container:release web -a $HEROKU_APP_NAME;
    branch: master